### ISSUE TITLE
when immediate is true, set method seems not working correctly. 

### ISSUE THREAD

**Issue by caoer** [jin5354/leaf-observable#1] opened 2017-08-03 05:38 UTC
```
test('image name', async t => {
  let imageStore = {
    image: {
      imageName: 'image-name',
    },
  };

  observify(imageStore);

  watch(
    () => {
      return imageStore.image;
    },
    (newVal, oldVal) => {
      console.info(`${JSON.stringify(oldVal)} => ${JSON.stringify(newVal)}`);
    },
    {
       deep: true
       immediate: true,
    }
  );

 // imageStore.image = { imageName: '1234' };
  set(imageStore, 'image', { imageName: 'aname' });
  // imageStore.image.tintColor = '12345';
  set(imageStore.image, 'tintColor', '54321');
});
```

expect
            {"imageName":"image-name"} => {"imageName":"aname","tintColor":"54321"}
but got: 
            {"imageName":"1234"} => {"imageName":"aname"}

for tintColor setter, the callback seems being ignored..

**Comment by jin5354** [comment] 2017-08-21 03:38
Thanks for your feedback! This issue caused by a missing assignment in observable.js L128.

```javascript
observify(newValue, false)
```
should be
```javascript
ob = observify(newValue, false)
```
The missing assignment leads to the var ob which points to key's __observer__ property didn't be updated after the key was rewritten. It has been fixed in the latest commit with new test case.

**Closed as completed by jin5354** 2017-08-21 03:38 UTC
